name: Smoke Suite
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v3
        - name: Setup Node.js environment
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install Dependencies
          run: npm install
        - name: Run Test
          run: npm run test
          continue-on-error: true
        - name: Generate Allure Repor
          run: npm run report:ci
        - name: Upload Allure Report to Artifact
          uses: actions/upload-artifact@v3
          with:
            name: AllureReport
            path: ./allure-report