name: WebdriverIO Test Suite
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v3
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install Packages
          run: npm ci
        - name: Run Test
          run: npm run smoke

  regression_on_chrome:
    needs: [smoke]
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v3
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install Dependencies
          run: npm ci
        - name: Run Test
          run: npm run test
        - name: Generate Allure Report
          if: always()
          run: npm run report:html
        - name: Upload Allure Report to Artifact
          if: always()
          uses: actions/upload-artifact@v3
          with:
            name: AllureReportChrome
            path: ./allure-report